name: publish

on: [push]

jobs:
  publish-base-srcds-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build uncletopia-srcds image
      run: |
        docker build . --tag ghcr.io/leighmacdonald/uncletopia-srcds:${GITHUB_REF##*/}
        docker push ghcr.io/leighmacdonald/uncletopia-srcds:${GITHUB_REF##*/}

  deploy-staging:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish-base-srcds-image
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy image
        uses: appleboy/ssh-action@master
        env:
          BRANCH: "${GITHUB_REF##*/}"
        with:
          host: "${{ secrets.HOST }}"
          username: "${{ secrets.SSH_USERNAME }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          envs: SRCDS_TOKEN,SRCDS_HOSTNAME,SRCDS_PW,SRCDS_RCONPW,SRCDS_IP,BRANCH
          script: ./deploy_test-2.sh "${GITHUB_REF##*/}"

      - name: Success notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '{{ EVENT_PAYLOAD.repository.full_name }} has been deployed :)'

      - name: Failure notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '{ EVENT_PAYLOAD.repository.full_name }} failed to deploy :('